import {StatusBar, StyleSheet, View} from 'react-native';
import React from 'react';

export default StyleSheet.create({
  container: {
    backgroundColor: '#f9f8f7',
    flex: 1,
  },
  redText: {
    color: 'red',
    fontFamily: 'FuturaDemiC',
  },
  blackText: {
    color: 'black',
    fontFamily: 'FuturaDemiC',
  },
  inputStyle: {
    fontFamily: 'FuturaDemiC',
    borderWidth: 1,
    borderColor: 'black',
    paddingTop: 20,
    paddingBottom: 18,
    paddingHorizontal: 5,
  },
  stepInput: {
    width: '80%',
    fontFamily: 'FuturaDemiC',
    borderWidth: 1,
    borderColor: '#21a33e',
    marginTop: 100,
    fontSize: 20,
    paddingTop: 20,
    paddingBottom: 18,
    textAlign: 'center',
    color: 'black',
    backgroundColor: 'white',
    paddingHorizontal: 5,
  },
  stepInputBase: {
    width: '80%',
    borderColor: '#bdbdbd',
    color: 'black',
    backgroundColor: 'white',
    fontFamily: 'FuturaDemiC',
    borderWidth: 1,
    marginTop: 100,
    paddingTop: 20,
    paddingBottom: 18,
    fontSize: 20,
    textAlign: 'center',
    paddingHorizontal: 5,
  },
  Input: {
    borderColor: '#21a33e',
    color: 'black',
    backgroundColor: 'white',

    fontFamily: 'FuturaDemiC',
    borderWidth: 1,
    paddingTop: 20,
    paddingBottom: 18,
    fontSize: 20,
    paddingHorizontal: 5,
  },
  InputBase: {
    borderColor: '#bdbdbd',
    color: 'black',
    backgroundColor: 'white',
    fontFamily: 'FuturaDemiC',
    borderWidth: 1,
    paddingTop: 20,
    paddingBottom: 18,
    fontSize: 20,
    paddingHorizontal: 5,
  },
  inputStyleError: {
    width: '80%',
    color: 'black',
    borderColor: 'red',
    backgroundColor: 'white',
    fontFamily: 'FuturaDemiC',
    borderWidth: 1,
    paddingTop: 20,
    paddingBottom: 18,
    fontSize: 20,
    paddingHorizontal: 5,
  },
  inputStyleErrorMain: {
    width: '100%',
    color: 'black',
    borderColor: 'red',
    backgroundColor: 'white',
    fontFamily: 'FuturaDemiC',
    borderWidth: 1,
    paddingTop: 20,
    paddingBottom: 18,
    fontSize: 20,
    paddingHorizontal: 5,
  },
  buttonActive: {
    backgroundColor: '#21a33e',
    marginVertical: 15,
    paddingVertical: 10,
    opacity: 1,
    fontFamily: 'FuturaDemiC',
    borderRadius: 35,
    fontSize: 35,
    width: '80%',
  },
  MainButton: {
    marginTop: 40,
    backgroundColor: '#21a33e',
    borderRadius: 35,
    marginVertical: 15,
    paddingVertical: 10,
    fontSize: 35,
    fontFamily: 'FuturaDemiC',
  },
  buttonDisable: {
    fontFamily: 'FuturaDemiC',
    borderRadius: 35,
    opacity: 0.3,
    backgroundColor: '#21a33e',
    marginVertical: 15,
    paddingVertical: 10,
    fontSize: 35,
    width: '80%',
  },
  button: {},
});
